Load the CSV into a DataFrame:

In [1]:
import pandas as pd

df = pd.read_csv('titanic.csv')

print(df.to_string())

     PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C
2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S
4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S
5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q
6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S
7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S
8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S
9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C
10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S
11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S
12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S
14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S
15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S
16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q
17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S
18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S
19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C
20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S
21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S
22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q
23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S
24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S
25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S
26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C
27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                                                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q
29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S
30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C
31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C
32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q
33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S
36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C
37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S
39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C
40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S
41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S
42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C
43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q
45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q
47            48         1       3                                                           O'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q
48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C
49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S
50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S
51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C
53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S
54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C
55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S
56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C
58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C
61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN
62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S
63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S
64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C
66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S
69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S
70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C
74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S
75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S
76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S
77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S
78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S
79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S
80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S
81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S
82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q
83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S
84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S
86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S
90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S
91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S
92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S
95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S
96            97         0       1                                                           Goldschmidt, Mr. George B    male  71.00      0      0            PC 17754   34.6542               A5        C

Print the DataFrame without the to_string() method:

In [2]:
import pandas as pd

df = pd.read_csv('titanic.csv')

print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Check the number of maximum returned rows:

In [3]:
import pandas as pd

print(pd.options.display.max_rows)

60

Increase the maximum number of rows to display the entire DataFrame:

In [4]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('titanic.csv')

print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
5              6         0       3
6              7         0       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
11            12         1       1
12            13         0       3
13            14         0       3
14            15         0       3
15            16         1       2
16            17         0       3
17            18         1       2
18            19         0       3
19            20         1       3
20            21         0       2
21            22         1       2
22            23         1       3
23            24         1       1
24            25         0       3
25            26         1       3
26            27         0       3
27            28         0       1
28            29         1       3
29            30         0       3
30            31         0       1
31            32         1       1
32            33         1       3
33            34         0       2
34            35         0       1
35            36         0       1
36            37         1       3
37            38         0       3
38            39         0       3
39            40         1       3
40            41         0       3
41            42         0       2
42            43         0       3
43            44         1       2
44            45         1       3
45            46         0       3
46            47         0       3
47            48         1       3
48            49         0       3
49            50         0       3
50            51         0       3
51            52         0       3
52            53         1       1
53            54         1       2
54            55         0       1
55            56         1       1
56            57         1       2
57            58         0       3
58            59         1       2
59            60         0       3
60            61         0       3
61            62         1       1
62            63         0       1
63            64         0       3
64            65         0       1
65            66         1       3
66            67         1       2
67            68         0       3
68            69         1       3
69            70         0       3
70            71         0       2
71            72         0       3
72            73         0       2
73            74         0       3
74            75         1       3
75            76         0       3
76            77         0       3
77            78         0       3
78            79         1       2
79            80         1       3
80            81         0       3
81            82         1       3
82            83         1       3
83            84         0       1
84            85         1       2
85            86         1       3
86            87         0       3
87            88         0       3
88            89         1       1
89            90         0       3
90            91         0       3
91            92         0       3
92            93         0       1
93            94         0       3
94            95         0       3
95            96         0       3
96            97         0       1
97            98         1       1
98            99         1       2
99           100         0       2
100          101         0       3
101          102         0       3
102          103         0       1
103          104         0       3
104          105         0       3
105          106         0       3
106          107         1       3
107          108         1       3
108          109         0       3
109          110         1       3
110          111         0       1
111          112         0       3
112          113         0       3
113          114         0       3
114          115         0       3
115          116         0       3
116          117         0       3
117          118         0       2
118          119         0       1
119          120         0       3
120          121         0       2
121          122         0       3
122          123         0       2
123          124         1       2
124          125         0       1
125          126         1       3
126          127         0       3
127          128         1       3
128          129         1       3
129          130         0       3
130          131         0       3
131          132         0       3
132          133         0       3
133          134         1       2
134          135         0       2
135          136         0       2
136          137         1       1
137          138         0       1
138          139         0       3
139          140         0       1
140          141         0       3
141          142         1       3
142          143         1       3
143          144         0       3
144          145         0       2
145          146         0       2
146          147         1       3
147          148         0       3
148          149         0       2
149          150         0       2
150          151         0       2
151          152         1       1
152          153         0       3
153          154         0       3
154          155         0       3
155          156         0       1
156          157         1       3
157          158         0       3
158          159         0       3
159          160         0       3
160          161         0       3
161          162         1       2
162          163         0       3
163          164         0       3
164          165         0       3
165          166         1       3
166          167         1       1
167          168         0       3
168          169         0       1
169          170         0       3
170          171         0       1
171          172         0       3
172          173         1       3
173          174         0       3
174          175         0       1
175          176         0       3
176          177         0       3
177          178         0       1
178          179         0       2
179          180         0       3
180          181         0       3
181          182         0       2
182          183         0       3
183          184         1       2
184          185         1       3
185          186         0       1
186          187         1       3
187          188         1       1
188          189         0       3
189          190         0       3
190          191         1       2
191          192         0       2
192          193         1       3
193          194         1       2
194          195         1       1
195          196         1       1
196          197         0       3
197          198         0       3
198          199         1       3
199          200         0       2
200          201         0       3
201          202         0       3
202          203         0       3
203          204         0       3
204          205         1       3
205          206         0       3
206          207         0       3
207          208         1       3
208          209         1       3
209          210         1       1
210          211         0       3
211          212         1       2
212          213         0       3
213          214         0       2
214          215         0       3
215          216         1       1
216          217         1       3
217          218         0       2
218          219         1       1
219          220         0       2
220          221         1       3
221          222         0       2
222          223         0       3
223          224         0       3
224          225         1       1
225          226         0       3
226          227         1       2
227          228         0       3
228          229         0       2
229          230         0       3
230          231         1       1
231          232         0       3
232          233         0       2
233          234         1       3
234          235         0       2
235          236         0       3
236          237         0       2
237          238         1       2
238          239         0       2
239          240         0       2
240          241         0       3
241          242         1       3
242          243         0       2
243          244         0       3
244          245         0       3
245          246         0       1
246          247         0       3
247          248         1       2
248          249         1       1
249          250         0       2
250          251         0       3
251          252         0       3
252          253         0       1
253          254         0       3
254          255         0       3
255          256         1       3
256          257         1       1
257          258         1       1
258          259         1       1
259          260         1       2
260          261         0       3
261          262         1       3
262          263         0       1
263          264         0       1
264          265         0       3
265          266         0       2
266          267         0       3
267          268         1       3
268          269         1       1
269          270         1       1
270          271         0       1
271          272         1       3
272          273         1       2
273          274         0       1
274          275         1       3
275          276         1       1
276          277         0       3
277          278         0       2
278          279         0       3
279          280         1       3
280          281         0       3
281          282         0       3
282          283         0       3
283          284         1       3
284          285         0       1
285          286         0       3
286          287         1       3
287          288         0       3
288          289         1       2
289          290         1       3
290          291         1       1
291          292         1       1
292          293         0       2
293          294         0       3
294          295         0       3
295          296         0       1
296          297         0       3
297          298         0       1
298          299         1       1
299          300         1       1
300          301         1       3
301          302         1       3
302          303         0       3
303          304         1       2
304          305         0       3
305          306         1       1
306          307         1       1
307          308         1       1
308          309         0       2
309          310         1       1
310          311         1       1
311          312         1       1
312          313         0       2
313          314         0       3
314          315         0       2
315          316         1       3
316          317         1       2
317          318         0       2
318          319         1       1
319          320         1       1
320          321         0       3
321          322         0       3
322          323         1       2
323          324         1       2
324          325         0       3
325          326         1       1
326          327         0       3
327          328         1       2
328          329         1       3
329          330         1       1
330          331         1       3
331          332         0       1
332          333         0       1
333          334         0       3
334          335         1       1
335          336         0       3
336          337         0       1
337          338         1       1
338          339         1       3
339          340         0       1
340          341         1       2
341          342         1       1
342          343         0       2
343          344         0       2
344          345         0       2
345          346         1       2
346          347         1       2
347          348         1       3
348          349         1       3
349          350         0       3
350          351         0       3
351          352         0       1
352          353         0       3
353          354         0       3
354          355         0       3
355          356         0       3
356          357         1       1
357          358         0       2
358          359         1       3
359          360         1       3
360          361         0       3
361          362         0       2
362          363         0       3
363          364         0       3
364          365         0       3
365          366         0       3
366          367         1       1
367          368         1       3
368          369         1       3
369          370         1       1
370          371         1       1
371          372         0       3
372          373         0       3
373          374         0       1
374          375         0       3
375          376         1       1
376          377         1       3
377          378         0       1
378          379         0       3
379          380         0       3
380          381         1       1
381          382         1       3
382          383         0       3
383          384         1       1
384          385         0       3
385          386         0       2
386          387         0       3
387          388         1       2
388          389         0       3
389          390         1       2
390          391         1       1
391          392         1       3
392          393         0       3
393          394         1       1
394          395         1       3
395          396         0       3
396          397         0       3
397          398         0       2
398          399         0       2
399          400         1       2
400          401         1       3
401          402         0       3
402          403         0       3
403          404         0       3
404          405         0       3
405          406         0       2
406          407         0       3
407          408         1       2
408          409         0       3
409          410         0       3
410          411         0       3
411          412         0       3
412          413         1       1
413          414         0       2
414          415         1       3
415          416         0       3
416          417         1       2
417          418         1       2
418          419         0       2
419          420         0       3
420          421         0       3
421          422         0       3
422          423         0       3
423          424         0       3
424          425         0       3
425          426         0       3
426          427         1       2
427          428         1       2
428          429         0       3
429          430         1       3
430          431         1       1
431          432         1       3
432          433         1       2
433          434         0       3
434          435         0       1
435          436         1       1
436          437         0       3
437          438         1       2
438          439         0       1
439          440         0       2
440          441         1       2
441          442         0       3
442          443         0       3
443          444         1       2
444          445         1       3
445          446         1       1
446          447         1       2
447          448         1       1
448          449         1       3
449          450         1       1
450          451         0       2
451          452         0       3
452          453         0       1
453          454         1       1
454          455         0       3
455          456         1       3
456          457         0       1
457          458         1       1
458          459         1       2
459          460         0       3
460          461         1       1
461          462         0       3
462          463         0       1
463          464         0       2
464          465         0       3
465          466         0       3
466          467         0       2
467          468         0       1
468          469         0       3
469          470         1       3
470          471         0       3
471          472         0       3
472          473         1       2
473          474         1       2
474          475         0       3
475          476         0       1
476          477         0       2
477          478         0       3
478          479         0       3
479          480         1       3
480          481         0       3
481          482         0       2
482          483         0       3
483          484         1       3
484          485         1       1
485          486         0       3
486          487         1       1
487          488         0       1
488          489         0       3
489          490         1       3
490          491         0       3
491          492         0       3
492          493         0       1
493          494         0       1
494          495         0       3
495          496         0       3
496          497         1       1
497          498         0       3
498          499         0       1
499          500         0       3
500          501         0       3
501          502         0       3
502          503         0       3
503          504         0       3
504          505         1       1
505          506         0       1
506          507         1       2
507          508         1       1
508          509         0       3
509          510         1       3
510          511         1       3
511          512         0       3
512          513         1       1
513          514         1       1
514          515         0       3
515          516         0       1
516          517         1       2
517          518         0       3
518          519         1       2
519          520         0       3
520          521         1       1
521          522         0       3
522          523         0       3
523          524         1       1
524          525         0       3
525          526         0       3
526          527         1       2
527          528         0       1
528          529         0       3
529          530         0       2
530          531         1       2
531          532         0       3
532          533         0       3
533          534         1       3
534          535         0       3
535          536         1       2
536          537         0       1
537          538         1       1
538          539         0       3
539          540         1       1
540          541         1       1
541          542         0       3
542          543         0       3
543          544         1       2
544          545         0       1
545          546         0       1
546          547         1       2
547          548         1       2
548          549         0       3
549          550         1       2
550          551         1       1
551          552         0       2
552          553         0       3
553          554         1       3
554          555         1       3
555          556         0       1
556          557         1       1
557          558         0       1
558          559         1       1
559          560         1       3
560          561         0       3
561          562         0       3
562          563         0       2
563          564         0       3
564          565         0       3
565          566         0       3
566          567         0       3
567          568         0       3
568          569         0       3
569          570         1       3